# Generated by Django 3.2.3 on 2021-06-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_msg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_name',
            new_name='name',
        ),
    ]
